services:
  # app:
  #   container_name: app
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  db:
    container_name: ci-runners-db
    image: postgres:14
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ci_runners
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
